#!/bin/bash

# config-lib.sh - Shared configuration module for opencode-dockerized
# This file is sourced by other scripts (not executed directly)
# Provides: config parsing, docker arg building, and interactive prompts

set -e

# ============================================
# CONSTANTS
# ============================================

CONFIG_DIR="${CONFIG_DIR:-$HOME/.config/opencode-dockerized}"
CONFIG_FILE="${CONFIG_FILE:-$CONFIG_DIR/config}"

# ============================================
# COLOR DEFINITIONS (with defaults if not set)
# ============================================

: "${RED:='\033[0;31m'}"
: "${GREEN:='\033[0;32m'}"
: "${YELLOW:='\033[1;33m'}"
: "${BLUE:='\033[0;34m'}"
: "${NC:='\033[0m'}"

# ============================================
# LOGGING FUNCTIONS (use caller's style if available)
# ============================================

config_info() {
    if type print_info >/dev/null 2>&1; then
        print_info "$1"
    else
        echo -e "${BLUE}ℹ${NC} $1"
    fi
}

config_success() {
    if type print_success >/dev/null 2>&1; then
        print_success "$1"
    else
        echo -e "${GREEN}✓${NC} $1"
    fi
}

config_warning() {
    if type print_warning >/dev/null 2>&1; then
        print_warning "$1"
    else
        echo -e "${YELLOW}⚠${NC} $1"
    fi
}

config_error() {
    if type print_error >/dev/null 2>&1; then
        print_error "$1"
    else
        echo -e "${RED}✗${NC} $1"
    fi
}

# ============================================
# CONFIG STATE (global arrays, populated by parse_config)
# ============================================

declare -a CUSTOM_MOUNTS=()      # Array of "host_path:container_path[:rw]"
declare -a CUSTOM_ENV_VARS=()    # Array of "VARIABLE_NAME"

# ============================================
# CONFIG FILE OPERATIONS
# ============================================

# Check if config file exists
config_exists() {
    [ -f "$CONFIG_FILE" ]
}

# Initialize config file with header
init_config_file() {
    mkdir -p "$CONFIG_DIR"
    cat > "$CONFIG_FILE" << 'EOF'
# OpenCode Dockerized User Configuration
# Generated by setup.sh - edit manually or re-run setup.sh to modify

# Custom volume mounts (read-only by default)
# Format: mount.<name>=<host_path>:<container_path>[:rw]
# Examples:
#   mount.gitconfig=~/.gitconfig:/home/coder/.gitconfig
#   mount.ssh=~/.ssh:/home/coder/.ssh:rw
#   mount.gitignore_global=~/.config/git/gitignore_global:/home/coder/.config/git/gitignore_global

# Environment variables to pass from host to container
# Format: env.<name>=<variable_name>
# Examples:
#   env.ssh_auth_sock=SSH_AUTH_SOCK
#   env.aws_bedrock=AWS_BEARER_TOKEN_BEDROCK
#   env.context7=CONTEXT7_API_KEY
EOF
    config_success "Created config file at $CONFIG_FILE"
}

# Load config file into arrays
load_config() {
    if ! config_exists; then
        config_warning "Config file not found at $CONFIG_FILE"
        return 1
    fi
    
    CUSTOM_MOUNTS=()
    CUSTOM_ENV_VARS=()
    
    # Read mounts (lines starting with "mount.")
    while IFS='=' read -r key value; do
        [[ "$key" =~ ^[[:space:]]*mount\. ]] || continue
        # Remove leading/trailing whitespace
        value="${value#"${value%%[![:space:]]*}"}"
        value="${value%"${value##*[![:space:]]}"}"
        [ -n "$value" ] && CUSTOM_MOUNTS+=("$value")
    done < "$CONFIG_FILE"
    
    # Read env vars (lines starting with "env.")
    while IFS='=' read -r key value; do
        [[ "$key" =~ ^[[:space:]]*env\. ]] || continue
        # Remove leading/trailing whitespace
        value="${value#"${value%%[![:space:]]*}"}"
        value="${value%"${value##*[![:space:]]}"}"
        [ -n "$value" ] && CUSTOM_ENV_VARS+=("$value")
    done < "$CONFIG_FILE"
    
    return 0
}

# Save current arrays to config file
save_config() {
    mkdir -p "$CONFIG_DIR"
    
    {
        echo "# OpenCode Dockerized User Configuration"
        echo "# Generated by setup.sh - edit manually or re-run setup.sh to modify"
        echo ""
        echo "# Custom volume mounts (read-only by default)"
        echo "# Format: mount.<name>=<host_path>:<container_path>[:rw]"
        
        if [ ${#CUSTOM_MOUNTS[@]} -gt 0 ]; then
            for i in "${!CUSTOM_MOUNTS[@]}"; do
                echo "mount.custom$(($i + 1))=${CUSTOM_MOUNTS[$i]}"
            done
        fi
        
        echo ""
        echo "# Environment variables to pass from host to container"
        echo "# Format: env.<name>=<variable_name>"
        
        if [ ${#CUSTOM_ENV_VARS[@]} -gt 0 ]; then
            for i in "${!CUSTOM_ENV_VARS[@]}"; do
                echo "env.custom$(($i + 1))=${CUSTOM_ENV_VARS[$i]}"
            done
        fi
    } > "$CONFIG_FILE"
    
    config_success "Saved configuration to $CONFIG_FILE"
}

# ============================================
# CONFIG PARSING (used at runtime by all scripts)
# ============================================

# Parse config file into global arrays
parse_config() {
    load_config || return 0  # Continue even if load fails
}

# Build docker volume mount arguments from CUSTOM_MOUNTS array
# Returns string like: "-v /path:/path -v /path2:/path2"
build_mount_args() {
    local mount_args=""
    
    for mount in "${CUSTOM_MOUNTS[@]}"; do
        # Expand ~ to home directory
        mount="${mount/\~/$HOME}"
        
        # Extract host_path, container_path, and mode
        local host_path="${mount%%:*}"
        local rest="${mount#*:}"
        local container_path="${rest%:*}"
        local mode="${rest##*:}"
        
        # Validate mode is either not set or "rw"
        if [ "$mode" = "$container_path" ]; then
            # No mode specified, default to read-only
            mount_args="$mount_args -v \"$host_path:$container_path:ro\""
        elif [ "$mode" = "rw" ]; then
            mount_args="$mount_args -v \"$host_path:$container_path:rw\""
        else
            # Mode was specified, use it as-is
            mount_args="$mount_args -v \"$host_path:$container_path:$mode\""
        fi
    done
    
    echo "$mount_args"
}

# Build docker environment variable arguments from CUSTOM_ENV_VARS array
# Returns string like: "-e VAR1=$VAR1 -e VAR2=$VAR2"
build_env_args() {
    local env_args=""
    
    for var_name in "${CUSTOM_ENV_VARS[@]}"; do
        # Get the value from the current environment
        local var_value="${!var_name}"
        
        # Only add if the variable is set in the environment
        if [ -n "$var_value" ]; then
            env_args="$env_args -e \"$var_name=$var_value\""
        else
            config_warning "Environment variable '$var_name' not set in host environment (skipping)"
        fi
    done
    
    echo "$env_args"
}

# ============================================
# CONFIG MANAGEMENT (used by setup.sh)
# ============================================

# Add a mount entry to arrays and optionally save
# add_mount <host_path> <container_path> [rw]
add_mount() {
    local host_path="$1"
    local container_path="$2"
    local mode="${3:-}"
    
    if [ -z "$host_path" ] || [ -z "$container_path" ]; then
        config_error "add_mount requires host_path and container_path"
        return 1
    fi
    
    # Validate host path exists
    local expanded_path="${host_path/\~/$HOME}"
    if [ ! -e "$expanded_path" ]; then
        config_warning "Host path does not exist: $expanded_path"
    fi
    
    if [ -n "$mode" ] && [ "$mode" != "ro" ] && [ "$mode" != "rw" ]; then
        config_error "Invalid mode: $mode (must be 'ro' or 'rw')"
        return 1
    fi
    
    local mount_entry="$host_path:$container_path"
    [ -n "$mode" ] && mount_entry="$mount_entry:$mode"
    
    CUSTOM_MOUNTS+=("$mount_entry")
}

# Add an environment variable entry to arrays
# add_env_var <VARIABLE_NAME>
add_env_var() {
    local var_name="$1"
    
    if [ -z "$var_name" ]; then
        config_error "add_env_var requires variable name"
        return 1
    fi
    
    CUSTOM_ENV_VARS+=("$var_name")
}

# Remove a mount entry by index
# remove_mount <index>
remove_mount() {
    local index="$1"
    
    if [ -z "$index" ]; then
        config_error "remove_mount requires index"
        return 1
    fi
    
    if [ "$index" -lt 0 ] || [ "$index" -ge ${#CUSTOM_MOUNTS[@]} ]; then
        config_error "Invalid index: $index"
        return 1
    fi
    
    unset 'CUSTOM_MOUNTS[$index]'
    CUSTOM_MOUNTS=("${CUSTOM_MOUNTS[@]}")  # Reindex array
}

# Remove an env var entry by index
# remove_env_var <index>
remove_env_var() {
    local index="$1"
    
    if [ -z "$index" ]; then
        config_error "remove_env_var requires index"
        return 1
    fi
    
    if [ "$index" -lt 0 ] || [ "$index" -ge ${#CUSTOM_ENV_VARS[@]} ]; then
        config_error "Invalid index: $index"
        return 1
    fi
    
    unset 'CUSTOM_ENV_VARS[$index]'
    CUSTOM_ENV_VARS=("${CUSTOM_ENV_VARS[@]}")  # Reindex array
}

# ============================================
# INTERACTIVE PROMPTS (used by setup.sh)
# ============================================

# Suggest a container path based on host path
# suggest_container_path <host_path> [default]
suggest_container_path() {
    local host_path="$1"
    local default="${2:-/home/coder/$(basename "$host_path")}"
    
    # For common paths, suggest sensible defaults
    if [[ "$host_path" == *"/.gitconfig" ]]; then
        echo "/home/coder/.gitconfig"
    elif [[ "$host_path" == *"/.ssh" ]]; then
        echo "/home/coder/.ssh"
    elif [[ "$host_path" == *"/.config/git"* ]]; then
        echo "/home/coder/.config/git/$(basename "$host_path")"
    elif [[ "$host_path" == *"/.gradle"* ]]; then
        echo "/home/coder/.gradle/$(basename "$host_path")"
    else
        echo "$default"
    fi
}

# Ask user how to handle existing config
# Sets global: CONFIG_MODE ("append", "overwrite", or "skip")
prompt_config_mode() {
    if ! config_exists; then
        CONFIG_MODE="new"
        return 0
    fi
    
    echo ""
    config_info "Configuration file already exists at $CONFIG_FILE"
    
    PS3="Choose an option: "
    select mode in "Append (add new entries)" "Overwrite (replace config)" "Skip (keep existing)"; do
        case "$mode" in
            "Append (add new entries)")
                CONFIG_MODE="append"
                config_success "Will append new entries to existing config"
                break
                ;;
            "Overwrite (replace config)")
                CONFIG_MODE="overwrite"
                config_warning "Will replace existing config"
                break
                ;;
            "Skip (keep existing)")
                CONFIG_MODE="skip"
                config_info "Skipping config setup"
                break
                ;;
            *)
                config_error "Invalid option"
                ;;
        esac
    done
}

# Interactive mount addition
# Prompts user repeatedly until they enter a blank line
prompt_custom_mounts() {
    echo ""
    config_info "Configure custom volume mounts (optional)"
    echo "Enter host paths to mount in the container (read-only by default)"
    echo "Press Enter with empty input to finish"
    echo ""
    
    while true; do
        read -p "Host path: " host_path
        
        # Allow blank to exit
        if [ -z "$host_path" ]; then
            break
        fi
        
        # Expand ~ for validation
        local expanded_path="${host_path/\~/$HOME}"
        
        if [ ! -e "$expanded_path" ]; then
            config_warning "Path does not exist: $expanded_path"
            read -p "Continue anyway? (y/N): " -r proceed
            [[ "$proceed" =~ ^[Yy]$ ]] || continue
        fi
        
        # Suggest container path
        local suggested=$(suggest_container_path "$host_path")
        read -p "Container path [$suggested]: " container_path
        container_path="${container_path:-$suggested}"
        
        # Ask about read-write
        read -p "Read-write? (y/N): " -r rw_mode
        local mode=""
        if [[ "$rw_mode" =~ ^[Yy]$ ]]; then
            mode="rw"
        fi
        
        # Add the mount
        add_mount "$host_path" "$container_path" "$mode"
        config_success "Added mount: $host_path -> $container_path${mode:+ ($mode)}"
        echo ""
    done
}

# Interactive environment variable addition
# Prompts user repeatedly until they enter a blank line
prompt_env_vars() {
    echo ""
    config_info "Configure environment variables (optional)"
    echo "Specify host environment variables to pass to the container"
    echo "Press Enter with empty input to finish"
    echo ""
    
    echo "Common examples:"
    echo "  SSH_AUTH_SOCK - For SSH key authentication"
    echo "  SSH_CLIENT, SSH_CONNECTION, SSH_TTY - SSH connection info"
    echo "  AWS_BEARER_TOKEN_BEDROCK - AWS Bedrock API key"
    echo "  CONTEXT7_API_KEY - Context7 API key"
    echo ""
    
    while true; do
        read -p "Environment variable name: " var_name
        
        # Allow blank to exit
        if [ -z "$var_name" ]; then
            break
        fi
        
        # Validate variable name (basic check)
        if ! [[ "$var_name" =~ ^[A-Z_][A-Z0-9_]*$ ]]; then
            config_error "Invalid variable name: $var_name (must be uppercase with underscores)"
            continue
        fi
        
        # Check if variable is set in environment
        if [ -z "${!var_name}" ]; then
            config_warning "Variable '$var_name' is not set in current environment"
            read -p "Add anyway? (y/N): " -r proceed
            [[ "$proceed" =~ ^[Yy]$ ]] || continue
        fi
        
        # Add the variable
        add_env_var "$var_name"
        config_success "Added environment variable: $var_name"
        echo ""
    done
}

# Print current configuration (for debugging/info)
print_config() {
    echo ""
    echo "Current configuration:"
    echo "  Config file: $CONFIG_FILE"
    
    if [ ${#CUSTOM_MOUNTS[@]} -gt 0 ]; then
        echo ""
        echo "  Custom mounts:"
        for i in "${!CUSTOM_MOUNTS[@]}"; do
            echo "    [$i] ${CUSTOM_MOUNTS[$i]}"
        done
    else
        echo ""
        echo "  Custom mounts: (none)"
    fi
    
    if [ ${#CUSTOM_ENV_VARS[@]} -gt 0 ]; then
        echo ""
        echo "  Environment variables:"
        for i in "${!CUSTOM_ENV_VARS[@]}"; do
            echo "    [$i] ${CUSTOM_ENV_VARS[$i]}"
        done
    else
        echo ""
        echo "  Environment variables: (none)"
    fi
    echo ""
}

# ============================================
# SETUP ORCHESTRATION (used by setup.sh)
# ============================================

# Main entry point for interactive configuration setup
# Handles: mode selection, prompts, config persistence
interactive_config_setup() {
    prompt_config_mode
    
    case "$CONFIG_MODE" in
        skip)
            echo ""
            echo "Skipping custom configuration setup."
            echo "You can run setup.sh again later to configure custom mounts and environment variables."
            ;;
        append|overwrite)
            [ "$CONFIG_MODE" = "append" ] && load_config
            prompt_custom_mounts
            prompt_env_vars
            save_config
            print_config
            ;;
        new)
            read -p "Would you like to configure custom mounts and environment variables now? (y/N): " -r setup_custom
            if [[ "$setup_custom" =~ ^[Yy]$ ]]; then
                prompt_custom_mounts
                prompt_env_vars
                if [ ${#CUSTOM_MOUNTS[@]} -gt 0 ] || [ ${#CUSTOM_ENV_VARS[@]} -gt 0 ]; then
                    save_config
                    print_config
                else
                    config_info "No custom configuration added."
                fi
            else
                init_config_file
                config_info "You can run setup.sh again later to configure custom mounts and environment variables."
            fi
            ;;
    esac
}
